"""Render research/ledger.json and the literature verdicts as docs/results.md.

The literature verdict of a result (corpus/literature.toml ``[[collisions]]``) overrides the
solver-side ``novelty_status`` of every ledger row it lists. ``--check`` exits non-zero when the
file on disk differs from a fresh render.
"""

from __future__ import annotations

import json
import sys
import tomllib

from research.lab import LEDGER_PATH, ROOT

RESULTS = ROOT / "docs" / "results.md"
LITERATURE = ROOT / "corpus" / "literature.toml"
JOURNAL = "journal/2026-09-22-turn-1.md"


def _cell(text: str, limit: int | None = None) -> str:
    text = text.replace("|", "/").replace("\n", " ")
    if limit is not None and len(text) > limit:
        text = text[: limit - 3] + "..."
    return text


def render() -> str:
    entries = json.loads(LEDGER_PATH.read_text())["entries"]
    collisions = tomllib.loads(LITERATURE.read_text())["collisions"]
    known = {e["candidate_id"] for e in entries}
    verdict_of: dict[str, str] = {}
    for c in collisions:
        for candidate in c["ledger"]:
            if candidate not in known:
                raise ValueError(f"{c['result']} lists unknown ledger row {candidate}")
            if candidate in verdict_of:
                raise ValueError(f"{candidate} is listed by two results")
            verdict_of[candidate] = f"{c['result']}: {c['verdict']}"
    lines = [
        "# Results register",
        "",
        "Generated by `just docs` from `research/ledger.json` and `corpus/literature.toml`.",
        "Do not edit by hand. The R-numbered results are written up in",
        f"[{JOURNAL}]({JOURNAL}).",
        "",
        "## Named results",
        "",
        "| result | verdict | ledger rows | known | open |",
        "|---|---|---|---|---|",
    ]
    for c in collisions:
        lines.append(
            f"| {c['result']} | {c['verdict']} | {', '.join(c['ledger'])} | "
            f"{_cell(c['known'])} | {_cell(c['open'])} |"
        )
    lines += [
        "",
        "## Ledger",
        "",
        "Novelty is the literature verdict where one exists, otherwise the solver-side status.",
        "",
        "| candidate | status | scope label | tier | novelty | result |",
        "|---|---|---|---|---|---|",
    ]
    for e in entries:
        novelty = verdict_of.get(e["candidate_id"], e["novelty_status"])
        lines.append(
            f"| {e['candidate_id']} | {e['status']} | {e['result_scope']} | "
            f"{e['formalization_tier']} | {_cell(novelty)} | {_cell(e['result'], 220)} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not RESULTS.exists() or RESULTS.read_text() != text:
            print(f"{RESULTS.relative_to(ROOT)} is stale; run `just docs`", file=sys.stderr)
            return 1
        return 0
    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    RESULTS.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
